In [9]:
import pandas as pd

In [ ]:
df = pd.read_csv("../Techteam/Data/FY-23-LegSheets - Better Maps Update (1).xlsx - Senate.csv")

In [22]:
schools = pd.read_csv("../Techteam/Data/FY-23-LegSheets - Better Maps Update (1).xlsx - Senate.csv")
schools = schools[["Type", "SCHOOL DISTRICT", "ENROLLMENT", "% OF FULL \nFUNDING", "TOTAL GAP TO FULL FUNDING", "PER PUPIL GAP TO FULL FUNDING"]]
schools

,Type,SCHOOL DISTRICT,ENROLLMENT,% OF FULL \nFUNDING,TOTAL GAP TO FULL FUNDING,PER PUPIL GAP TO FULL FUNDING
0,16,WASHINGTON COMM H S DIST 308,1469.0,59%,"$7,827,163","$5,330"
1,16,WASHINGTON COMM H S DIST 308,1469.0,59%,"$7,827,163","$5,330"
2,2,CHANEY-MONGE SCH DISTRICT 88,476.0,59%,"$3,150,064","$6,618"
3,2,CHANEY-MONGE SCH DISTRICT 88,476.0,59%,"$3,150,064","$6,618"
4,2,CENTRAL CITY SCHOOL DIST 133,347.0,60%,"$1,796,465","$5,183"
...,...,...,...,...,...,...
1491,2,ROSEMONT ELEM SCHOOL DIST 78,195.0,249%,"-$4,217,323","-$21,600"
1492,2,RONDOUT SCHOOL DIST 72,144.0,269%,"-$3,098,107","-$21,572"
1493,2,RONDOUT SCHOOL DIST 72,144.0,269%,"-$3,098,107","-$21,572"
1494,16,OHIO COMMUNITY H S DIST 505,32.0,270%,"-$757,919","-$23,947"
1495,30,NaN,NaN,NaN,NaN,NaN

In [25]:
legislators = pd.read_csv("../Techteam/Data/103rd GA Legislators.xlsx - 103rd Senate.csv")
legislators = legislators[["Senator", "District"]]
legislators

                      Senator  District
0          Javier L Cervantes         1
1                 Omar Aquino         2
2               Mattie Hunter         3
3       Kimberly A. Lightford         4
4           Patricia Van Pelt         5
5            Sara Feigenholtz         6
6                Mike Simmons         7
7              Ram Villivalam         8
8                  Laura Fine         9
9          Robert F. Martwick        10
10              Mike Porfirio        11
11          Celina Villanueva        12
12              Robert Peters        13
13            Emil Jones, III        14
14       Napoleon Harris, III        15
15             Willie Preston        16
16         Elgie R. Sims, Jr.        17
17            Bill Cunningham        18
18        Michael E. Hastings        19
19  Cristina H. Pacione-Zayas        20
20               Laura Ellman        21
21            Cristina Castro        22
22        Suzy Glowiak Hilton        23
23                 Seth Lewis        24
24               Karina Villa        25
25              Dan McConchie        26
26              Ann Gillespie        27
27            Laura M. Murphy        28
28          Julie A. Morrison        29
29            Adriane Johnson        30
30            Mary Edly-Allen        31
31               Craig Wilcox        32
32          Donald P. DeWitte        33
33            Steve Stadelman        34
34              Dave Syverson        35
35          Michael W. Halpin        36
36                Win Stoller        37
37                  Sue Rezin        38
38                 Don Harmon        39
39           Patrick J. Joyce        40
40             John F. Curran        41
41               Linda Holmes        42
42             Rachel Ventura        43
43            Sally J. Turner        44
44          Andrew S. Chesney        45
45              David Koehler        46
46              Neil Anderson        47
47               Doris Turner        48
48        Meg Loughran Cappel        49
49                  Jil Tracy        50
50                Chapin Rose        51
51                Paul Faraci        52
52                Tom Bennett        53
53              Steve McClure        54
54              Jason Plummer        55
55              Erica Harriss        56
56           Christopher Belt        57
57               Terri Bryant        58
58                Dale Fowler        59